name: DiemSinhMenh
version: '${project.version}'
main: net.danh.diemsinhmenh.Main
softdepend: [ PlaceholderAPI ]
authors: [ VoChiDanh ]
description: Diem sinh menh cua nguoi choi
commands:
  souls:
    description: xem toan bo lenh cua plugin
    usage: /<commands>