name: SoulPoints
version: '${project.version}'
main: net.danh.diemsinhmenh.Main
softdepend: [ PlaceholderAPI ]
authors: [ VoChiDanh ]
description: SoulPoints for player
commands:
  souls:
    description: help command
    usage: /<commands>
