available-worlds:
  - world
  - world_nether
  - world_the_end
PVP:
  Enable: true
  Kill-souls: 1
  Kill-message: '&d[Souls] &bYou receive 1 Souls because you killed other player'
ActionBar:
  Enable: true
General:
  Default-amount-souls: 7
  Death-souls: 1
  Daily-souls: 60
  Respawn_souls: 3
  Lose-soul-message-after: 3
Message:
  Soul-earn-message: '&d[Souls] &fYou have earned 1 Soul!'
  Death-message: '&d[Souls] &fYou have lost 2 Soul, You have %souls% Souls Now!'
  Death-message-inventory: '&4[Souls] &cYou have lost all of your souls, your inventory has been dropped!'
  Take-message: '&4[Souls] &cRemove %souls% souls from %player%'
  Add-message: '&4[Souls] &cAdd %souls% souls to %player%'
  Check-message: '&4[Souls] &c%player% has %souls%'
  Soul-message: '&d[Souls] &fYou have %souls% souls!'
  Not-online: '&d[Souls] &cThat player is not online!'
  Enough: '&d[Souls] &cToo much amount to remove!'
  Reload: '&d[Souls] &cReload Config'
Help-player:
  - "&a/souls check <player> &f- &7Check souls of player"
Help-admin:
  - "§a/souls check <player> §f- §7Check souls of player"
  - "§a/souls add <player> <amount> §f- §7Add souls "
  - "§a/souls remove <player> <amount> §f- §7Remove souls"
  - "§a/souls reload §f- §7Reload Config"
config-version: 4
