name: SoulPoints
version: '1.2.3'
main: net.danh.diemsinhmenh.Main
softdepend: [ PlaceholderAPI ]
authors: [ VoChiDanh ]
description: SoulPoints for player
commands:
  souls:
    description: help command
    usage: /<commands>
