name: 'SoulPoints'
version: '1.2.5-R2'
main: net.danh.diemsinhmenh.Main
softdepend: [ PlaceholderAPI ]
authors: [ VoChiDanh ]
description: 'SoulsPoint for player'
commands:
  souls:
    description: help command
    usage: /<commands>