name: Build & Upload

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        run: mvn -B package
      - uses: "actions/upload-artifact@v3"
        with:
          name: "SoulPoints-SNAPSHOT"
          path: ./target/SoulPoints-Premium.jar

