name: Build & Upload

on:
  push:
    branches: [ master ]

jobs:
  build:
    if: contains(github.event.head_commit.message, '[BETA]')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: maven
      - name: Unshallow
        run: git fetch --unshallow --quiet
      - name: Build with Maven
        run: mvn -B package
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%H:%M %m/%d/%Y')"
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "v1.2.1"
          prerelease: false
          title: "v1.2.1 ${{ steps.date.outputs.date }}"
          files: |
            ./target/SoulPoints.jar
