name: Build & Upload

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: '1.8'
          distribution: 'adopt'
          cache: maven
      - name: Unshallow
        run: git fetch --unshallow --quiet
      - name: Build with Maven
        run: mvn -B package
      
      - name: Setup workspace
        run: |
          echo "GIT_COMMIT=${GITHUB_SHA}" >> $GITHUB_ENV
          echo "GIT_BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
      
        env:
          CI_SYSTEM: Github Actions
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%H:%M %m/%d/%Y')"
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Release ${{ steps.date.outputs.date }}"
          files: |
            /target/SoulPoints.jar
